name: Build & Release

on:
  # Event will trigger job
  push:
    # branches:
    # - main
    tags:
      - "v*"

jobs:
  build:
    name: Build
    # Run on macos operating system
    runs-on: macos-12
    steps:
      # Start clone from repo into macos
      - name: Clone repository
        uses: actions/checkout@v4

      # Extract version
      - name: Extract version
        id: extract_version
        run: |
          # From commit message
          # version=$(echo ${{ github.event.head_commit.message }} | grep -oP '(?<=Update: v)\d+\.\d+\.\d+')

          # From tag
          version=$(echo ${{ github.ref_name }} | grep -oP '(?<=v)\d+\.\d+\.\d+')
          echo "version=${version}" >> $GITHUB_OUTPUT

      # Setup Java env
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17.x"

      # Setup Flutter env
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml

      # Install Dependencies
      - name: Install depenencies
        run: flutter pub get

      # Check for any formatting issues in the code.
      - name: Check code formatting
        run: dart format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - name: Analyze Dart code
        run: flutter analyze .

      # Build Android for GitHub release
      # when use split-per-abi
      # - app-armeabi-v7a-release.apk: small file(most devices use this version)
      # - app-arm64-v8a.apk: medium file(new version e.g Sumsung)
      # - app-x86_64-release.apk: medium file(e.g intel)
      - name: Build arm64 APK
        run: flutter build apk --release --split-per-abi --target-platform="android-arm64" --flavor github

      # Release arm64 generated APK
      - name: Release arm64 APK
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: datdonguyen99/Elearning
          # Token repo, [setting -> developer settings -> personal access token -> ]
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-arm64-v8a-github-release.apk
          asset_name: Elearning-arm64-v8a.apk
          tag: ${{ steps.extract_version.outputs.version }}
          prerelease: false
          overwrite: true
